question_pool = [{"chapter": 15,
                 "section": 2,
                 "question #": 1,
                 "q": "Which of the following was the most prominent issue publicly debated after the Civil War?",
                 "answers": [("Proper compensation to the South for property lost in the war.", "incorrect"),
                             ("Proper compensation to the North for property lost in the war.", "incorrect"),
                             ("The concept of citizenship and who counts as a citizen.", "correct"),
                             ("Legitimacy of military tactics used in the war.", "incorrect")]},
                {"chapter": 15,
                 "section": 1,
                 "question #": 1,
                 "q": "“Reconstruction” was:",
                 "answers": [("An attempt to reincorporate the South into the Union "
                              "and redefine the role of black people in American society.", "correct"),
                             ("A government effort to reconstruct the infrastructure of the nation.", "incorrect"),
                             ("An effort by the South to rebuild itself after the war.", "incorrect"),
                             ("None of the answers given.", "incorrect")]},
                {"chapter": 15,
                 "section": 3,
                 "question #": 1,
                 "q": "Which of the following was a major concern expressed by freedpeople in the South?",
                 "answers": [("A public recognition of their pain and suffering.", "incorrect"),
                            ("A demand to punish former slaveowners.", "incorrect"),
                            ("A reestablishment of traditional African culture.", "incorrect"),
                            ("A desire to achieve ownership of land with government assistance.", "correct")]},
                {"chapter": 15,
                 "section": 3,
                 "question #": 2,
                 "q": "During Reconstruction, which of the following was a major function of black churches:",
                 "answers": [("Centralized leadership and organization.", "correct"),
                             ("Missing person’s bureau.", "incorrect"),
                             ("Business hubs.", "incorrect"),
                             ("Lending libraries.", "incorrect")]},
                 # TODO update chapter, section, and question numbers from this point on
                {"chapter": 15,
                 "section": 0,
                 "question #": 0,
                 "q": "The American Equal Rights Association (AERA) was divided over which question:",
                 "answers": [("Whether racial equality was possible.", "incorrect"),
                             ("Should the struggle for black male suffrage take precedence over universal suffrage.", "correct"),
                             ("Whether equality between the sexes was possible.", "incorrect"),
                             ("All of the answers given.", "incorrect")]},
                {"chapter": 15,
                 "section": 0,
                 "question #": 0,
                 "q": "What did proponents of the “Lost Cause” narrative try to do?",
                 "answers": [("Claim that reunification of the North and the South was a lost cause.", "incorrect"),
                             ("Convince southerners that getting compensation for their lost property was not possible.", "incorrect"),
                             ("Promote efforts to find family members lost during the war.", "incorrect"),
                             ("Deemphasize the brutality of slavery and claim the Civil War was about states’ rights.", "correct")]},
                {"chapter": 15,
                 "section": 0,
                 "question #": 0,
                 "q": "Many Black southern women who worked after the war...",
                 "answers": [("Continued to do the same work they had done before, under the same conditions.", "incorrect"),
                             ("Opened their own business establishments.", "incorrect"),
                             ("Worked in similar jobs as before but set their own wages and hours.", "correct"),
                             ("None of the answers given.", "incorrect")]},
                {"chapter": 15,
                 "section": 0,
                 "question #": 0,
                 "q": "What form did racial violence in the South take?",
                 "answers": [("Riots against black political authority.", "incorrect"),
                             ("Organized white vigilante groups attacking black people.", "incorrect"),
                             ("Interpersonal fights in which law enforcement protected white instigators.", "incorrect"),
                             ("All of the answers given.", "correct")]},
                {"chapter": 15,
                 "section": 0,
                 "question #": 0,
                 "q": "What terms does Jourdon Anderson set to his old master before considering working for him as a freedman?",
                 "answers": [("Backpay for his and his wife’s time of labor as slaves.", "correct"),
                             ("A public apology for past mistreatment.", "incorrect"),
                             ("A house he and his family could live in.", "incorrect"),
                             ("A chance to buy his own plot of land.", "incorrect")]},
                {"chapter": 15,
                 "section": 0,
                 "question #": 0,
                 "q": "What did Thaddeus Stevens propose in his speech on March 19, 1867?",
                 "answers": [("To immediately reincorporate the South into the Union.", "incorrect"),
                             ("To give full suffrage to Black men.", "incorrect"),
                             ("To confiscate southern property to pay for war damages and punish rebels.", "correct"),
                             ("All of the answers given.", "incorrect")]},
                {"chapter": 15,
                 "section": 0,
                 "question #": 0,
                 "q": "What was the most valuable asset of southern planters?",
                 "answers": [("Agricultural land.", "incorrect"),
                             ("Gold bars.", "incorrect"),
                             ("Slaves.", "correct"),
                             ("Industrial machinery.", "incorrect")]},
                {"chapter": 15,
                 "section": 0,
                 "question #": 0,
                 "q": "What economic change in the North was the result of the war?",
                 "answers": [("The establishment of a national income tax.", "incorrect"),
                             ("The creation of a fiat currency.", "incorrect"),
                             ("The rise of inflation.", "incorrect"),
                             ("All of the answers given.", "correct")]},
                {"chapter": 15,
                 "section": 0,
                 "question #": 0,
                 "q": "How was the Great Railroad Strike of 1877 finally resolved?",
                 "answers": [("Rail companies agreed to the workers’ terms.", "incorrect"),
                             ("Legislation was put in place to protect workers.", "incorrect"),
                             ("Local police, and state and federal troops suppressed it with violence.", "correct"),
                             ("The government negotiated a settlement between capital and labor.", "incorrect")]},
                {"chapter": 15,
                 "section": 0,
                 "question #": 0,
                 "q": "Why did investors put massive amounts of capital into corporations?",
                 "answers": [("New legislation made it possible to profit from them with few financial and legal obligations.", "correct"),
                             ("A national campaign encouraged investments.", "incorrect"),
                             ("Investing in other things was risky.", "incorrect"),
                             ("There was no more land available for investment.", "incorrect")]},
                {"chapter": 15,
                 "section": 0,
                 "question #": 0,
                 "q": "According to Samuel Gompers in “The American Federation of Labor (1883)” trade unions are:",
                 "answers": [("The outgrowth of socialist or communist ideas.", "incorrect"),
                             ("Only able to exist in Western countries.", "correct"),
                             ("A negative force in the United States.", "incorrect"),
                             ("None of the answers given.", "incorrect")]},
                ]
